from __future__ import annotations

REQUIREMENT_CATALOG = [
    {
        "id": "REQ-001",
        "requirement": "Local runnable demo with FastAPI and Streamlit",
        "artifacts": ["run_local_api.py", "app/ui/app_enterprise.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-002",
        "requirement": "UV package manager support",
        "artifacts": ["pyproject.toml"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-003",
        "requirement": "TigerGraph MCP library-based primary graph access",
        "artifacts": ["app/graph/tigergraph/mcp_library_client.py", "app/graph/access/graph_access_client.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-004",
        "requirement": "TigerGraph REST fallback and mock fallback",
        "artifacts": ["app/graph/tigergraph/rest_client.py", "app/graph/mock/mock_graph_data_service.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-005",
        "requirement": "All TigerGraph objects use phx_dm_ prefix",
        "artifacts": ["tigergraph/schema/01_vertices.gsql", "tigergraph/schema/02_edges.gsql"],
        "validation": "contains_phx_prefix",
        "priority": "Critical",
    },
    {
        "id": "REQ-006",
        "requirement": "Preloaded SQLite database exists and is populated",
        "artifacts": ["data/sqlite/iperform.db"],
        "validation": "sqlite_populated",
        "priority": "Critical",
    },
    {
        "id": "REQ-007",
        "requirement": "Preloaded Chroma folder exists",
        "artifacts": ["data/chroma/preloaded_chroma_manifest.json", "data/chroma/preloaded_knowledge_index.json"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-008",
        "requirement": "True agentic architecture with explicit agents",
        "artifacts": ["app/agents/registry/agent_registry.py", "app/agents/workflows/advisor_coaching_graph.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-009",
        "requirement": "LangGraph/LangChain dependencies present",
        "artifacts": ["pyproject.toml"],
        "validation": "contains_langgraph_langchain",
        "priority": "Critical",
    },
    {
        "id": "REQ-010",
        "requirement": "AI Assistant Chat as a separate page",
        "artifacts": ["app/ui/pages/ai_assistant_chat.py"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-011",
        "requirement": "Context Graph and Temporal Memory",
        "artifacts": ["app/graph/memory/memory_repository.py", "app/services/context_service.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-012",
        "requirement": "Feature Store and feature engineering",
        "artifacts": ["app/feature_store/feature_store_repository.py", "app/feature_store/feature_engineering.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-013",
        "requirement": "Graph embeddings and similarity",
        "artifacts": ["app/embeddings/embedding_engine.py", "app/embeddings/similarity_engine.py"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-014",
        "requirement": "Prediction engine",
        "artifacts": ["app/prediction/prediction_engine.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-015",
        "requirement": "Opportunity engine",
        "artifacts": ["app/opportunities/opportunity_engine.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-016",
        "requirement": "Recommendation engine",
        "artifacts": ["app/recommendations/recommendation_engine.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-017",
        "requirement": "Feedback learning loop",
        "artifacts": ["app/feedback/learning_signal_engine.py", "app/services/feedback_learning_service.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-018",
        "requirement": "AI Insights and Coaching cards",
        "artifacts": ["app/ai/insights/insight_generation_engine.py", "app/ui/pages/insights_coaching.py"],
        "validation": "file_exists",
        "priority": "Critical",
    },
    {
        "id": "REQ-019",
        "requirement": "Enterprise UI with persona and hierarchy scope selection",
        "artifacts": ["app/ui/components/navigation.py", "app/ui/app_enterprise.py"],
        "validation": "contains_persona_scope",
        "priority": "High",
    },
    {
        "id": "REQ-020",
        "requirement": "AGP goals and coaching",
        "artifacts": ["app/ui/pages/agp_goals_coaching.py", "tigergraph/sample_data/phx_dm_goal.csv", "tigergraph/sample_data/phx_dm_kpi.csv"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-021",
        "requirement": "CRM data support",
        "artifacts": ["tigergraph/sample_data/phx_dm_crm_activity.csv"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-022",
        "requirement": "Explainability evidence and reasoning",
        "artifacts": ["app/agents/nodes/explainability_agent.py", "app/models/insights_coaching.py"],
        "validation": "file_exists",
        "priority": "High",
    },
    {
        "id": "REQ-023",
        "requirement": "Documentation and installation guide",
        "artifacts": ["docs/README_OPERATIONS_INDEX.md", "docs/setup/01_fresh_machine_install.md", "runbooks/quick_start.md"],
        "validation": "file_exists",
        "priority": "Critical",
    },
]
