"use client";
import { useEffect, useState } from "react";
import { Activity, Bot, BrainCircuit, CheckCircle2, Database, FileText, GitBranch, Home, Network, Search, Target, TrendingUp, Upload, Users } from "lucide-react";
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart as RPieChart, Pie, Cell } from "recharts";
import { uiApi } from "@/lib/api/ui-remediation";

const colors = ["#2563eb", "#14b8a6", "#7c3aed", "#f97316", "#94a3b8"];
function cls(status?: string) {
  if (status === "good" || status === "Passed" || status === "Completed") return "border-emerald-200 bg-emerald-50 text-emerald-700";
  if (status === "bad" || status === "failed") return "border-red-200 bg-red-50 text-red-700";
  if (status === "warn" || status === "Review Required" || status === "Follow-up") return "border-amber-200 bg-amber-50 text-amber-700";
  return "border-slate-200 bg-white text-slate-700";
}
function PageFrame({title, children}: any) {
  return <div className="min-h-screen bg-slate-50">
    <div className="sticky top-0 z-10 border-b bg-white/95 px-4 py-3 backdrop-blur">
      <div className="flex items-center justify-between">
        <div><h1 className="text-[20px] font-black text-slate-950">{title}</h1><p className="text-[11px] text-slate-500">Real-time insights, predictions, recommendations & learning</p></div>
        <div className="flex items-center gap-2 text-[11px]"><span className="rounded-full bg-slate-100 px-2 py-1">Graph: MOCK</span><span className="rounded-full bg-blue-600 px-3 py-1 font-bold text-white">Ready</span></div>
      </div>
      <div className="mt-3 grid grid-cols-5 gap-2">{["Region","Region","New York Region","YTD","Prior Year"].map((f) => <select key={f} className="h-8 rounded-lg border bg-white px-2 text-[12px]"><option>{f}</option></select>)}</div>
    </div><main className="p-4">{children}</main></div>
}
function Section({title, icon:Icon=Activity, children, className=""}: any) {
  return <section className={`rounded-2xl border bg-white p-3 shadow-sm ${className}`}><div className="mb-3 flex items-center gap-2 text-[13px] font-black text-slate-900"><Icon className="h-4 w-4 text-blue-600"/>{title}</div>{children}</section>
}
function MetricCard({item}: any) {
  return <div className="rounded-xl border bg-white p-3 shadow-sm"><div className="text-[11px] font-semibold uppercase text-slate-500">{item.label}</div><div className="mt-2 text-[22px] font-black text-slate-950">{item.value}</div><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-[11px] font-bold ${cls(item.status)}`}>{item.delta}</span></div>
}
function StatusRow({item}: any) {
  return <div className={`mb-2 rounded-xl border p-3 text-[12px] ${cls(item.status)}`}><div className="flex items-center justify-between"><strong>{item.name ?? item.title ?? item.label}</strong><span className="font-black">{item.score ?? item.value ?? item.growth ?? item.status}</span></div>{item.reason && <div className="mt-1 text-slate-600">{item.reason}</div>}{item.impact && <div className="mt-1 font-semibold text-slate-800">Impact {item.impact}</div>}</div>
}
function AgentTrace({items}: any) { return <div className="flex flex-wrap gap-2 rounded-xl border bg-emerald-50 p-2">{(items ?? []).map((a: string) => <span key={a} className="rounded-full border border-emerald-200 bg-white px-2 py-1 text-[11px] font-semibold text-emerald-700"><CheckCircle2 className="mr-1 inline h-3 w-3"/>{a}</span>)}</div> }

export function DashboardRemediation() {
  const [data, setData] = useState<any>(); const [question, setQuestion] = useState("Why is my revenue down in the Downtown market?"); const [messages, setMessages] = useState<any[]>([]);
  useEffect(() => { uiApi.dashboard().then(setData); }, []);
  if (!data) return <PageFrame title="Advisor Revenue Intelligence & AI Coaching Copilot"><div>Loading...</div></PageFrame>;
  async function ask() { const res = await uiApi.assistant(question); setMessages([...messages, {role:"user", text:question}, {role:"assistant", text:res.answer}]); }
  return <PageFrame title="Advisor Revenue Intelligence & AI Coaching Copilot"><div className="grid grid-cols-[1fr_280px] gap-4"><div className="space-y-4">
    <div className="grid grid-cols-4 gap-3">{data.kpis.map((k:any)=><MetricCard key={k.label} item={k}/>)}</div>
    <div className="grid grid-cols-2 gap-4"><Section title="AI Insight Summary" icon={BrainCircuit}><h2 className="text-[16px] font-black">{data.insight.headline}</h2><p className="mt-2 text-[12px] leading-5 text-slate-600">{data.insight.summary}</p><div className="mt-3 grid grid-cols-3 gap-2">{data.insight.drivers.map((d:any)=><StatusRow key={d.label} item={d}/>)}</div></Section><Section title="AI Coaching Card" icon={Bot}><div className="space-y-2">{data.coaching.map((c:string)=><div key={c} className="rounded-xl border bg-emerald-50 p-3 text-[12px]"><CheckCircle2 className="mr-2 inline h-4 w-4 text-emerald-600"/>{c}</div>)}</div></Section></div>
    <div className="grid grid-cols-4 gap-4"><Section title="Revenue Trend" className="col-span-2" icon={TrendingUp}><div className="h-52"><ResponsiveContainer><LineChart data={data.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="revenue" stroke="#2563eb" strokeWidth={3}/><Line dataKey="managed" stroke="#14b8a6" strokeWidth={3}/><Line dataKey="prior" stroke="#94a3b8"/></LineChart></ResponsiveContainer></div></Section><Section title="Product Mix"><div className="h-52"><ResponsiveContainer><RPieChart><Pie data={data.mix} dataKey="value" nameKey="name" innerRadius={45}>{data.mix.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></RPieChart></ResponsiveContainer></div></Section><Section title="Opportunities" icon={Target}>{data.opportunities.map((o:any)=><StatusRow key={o.name} item={o}/>)}</Section></div>
    <div className="grid grid-cols-2 gap-4"><Section title="Top Recommendations">{data.recommendations.map((r:any)=><div key={r.name} className="mb-2 rounded-xl border p-3 text-[12px]"><div className="flex justify-between"><strong>{r.name}</strong><span>{r.confidence}%</span></div><div className="mt-2 flex gap-2"><button className="rounded bg-emerald-600 px-2 py-1 text-white">Accept</button><button className="rounded bg-red-600 px-2 py-1 text-white">Reject</button><button className="rounded bg-amber-500 px-2 py-1 text-white">Ignore</button></div></div>)}</Section><Section title="System Trace"><AgentTrace items={data.agentTrace}/></Section></div>
  </div><Section title="AI Chat Assistant" icon={Bot}><div className="h-[520px] space-y-2 overflow-auto rounded-xl bg-slate-50 p-2">{messages.length===0 && <div className="rounded-xl bg-white p-3 text-[12px] text-slate-600">Ask me about revenue, opportunities, recommendations, graph evidence, or next best actions.</div>}{messages.map((m,i)=><div key={i} className={`rounded-xl p-3 text-[12px] ${m.role==="user"?"bg-blue-600 text-white":"bg-white text-slate-700"}`}>{m.text}</div>)}</div><div className="mt-2 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} className="h-9 flex-1 rounded-lg border px-2 text-[12px]"/><button onClick={ask} className="rounded-lg bg-blue-600 px-3 text-white">Send</button></div></Section></div></PageFrame>
}

export function RevenueAnalyticsRemediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.revenue().then(setData)},[]); if(!data) return <PageFrame title="Revenue Analytics & Drilldown"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Revenue Analytics & Drilldown"><div className="space-y-4"><div className="grid grid-cols-4 gap-3">{data.kpis.map((k:any)=><MetricCard key={k.label} item={k}/>)}</div><div className="grid grid-cols-3 gap-4"><Section title="Revenue / AUM / NNM / NCF Trend" className="col-span-2" icon={TrendingUp}><div className="h-64"><ResponsiveContainer><LineChart data={data.trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip/><Line dataKey="revenue" stroke="#2563eb" strokeWidth={3}/><Line dataKey="nnm" stroke="#14b8a6"/><Line dataKey="ncf" stroke="#f97316"/></LineChart></ResponsiveContainer></div></Section><Section title="Top / Bottom Markets">{data.top.map((x:any)=><StatusRow key={x.name} item={{...x,status:"good"}}/>)}{data.bottom.map((x:any)=><StatusRow key={x.name} item={{...x,status:"bad"}}/>)}</Section></div><div className="grid grid-cols-2 gap-4"><Section title="Hierarchy Drilldown" icon={GitBranch}>{data.hierarchy.map((x:any)=><StatusRow key={x.name} item={{name:`${x.level}: ${x.name}`, value:`${x.revenue} · ${x.growth}`, status:x.status}}/>)}</Section><Section title="Transaction Detail" icon={Database}>{data.transactions.map((x:any)=><StatusRow key={x.date+x.household} item={{name:`${x.date} · ${x.household}`, value:`${x.product} · ${x.impact}`, status:x.status}}/>)}</Section></div></div></PageFrame>
}

export function Advisor360Remediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.advisor().then(setData)},[]); if(!data) return <PageFrame title="Advisor 360 / Client 360"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Advisor 360 / Client 360"><div className="space-y-4"><Section title="Advisor Profile" icon={Users}><div className="grid grid-cols-6 gap-3 text-[12px]"><div><strong>{data.profile.name}</strong><br/>{data.profile.role}</div><div>{data.profile.market}</div><div>{data.profile.region}</div><div>Health <strong>{data.profile.health}</strong></div><div>Risk <strong>{data.profile.risk}</strong></div><div className="rounded-full bg-amber-100 px-3 py-1 text-center font-bold text-amber-700">At Risk</div></div></Section><div className="grid grid-cols-4 gap-3">{data.kpis.slice(0,4).map((k:any)=><MetricCard key={k.label} item={k}/>)}</div><div className="grid grid-cols-2 gap-4"><Section title="Household Intelligence" icon={Home}>{data.households.map((h:any)=><StatusRow key={h.name} item={{name:h.name,value:`AUM ${h.aum} · NNM ${h.nnm} · ${h.action}`,status:h.status}}/>)}</Section><Section title="CRM Activity" icon={Activity}>{data.crm.map((c:any)=><StatusRow key={c.title} item={{name:c.title,value:`${c.date} · ${c.type}`,status:c.status}}/>)}</Section><Section title="Prediction Scores">{data.predictions.map((p:any)=><StatusRow key={p.label} item={p}/>)}</Section><Section title="Similar Advisors / Households" icon={Search}>{data.similar.map((s:any)=><StatusRow key={s.name} item={{name:s.name,value:s.similarity,reason:s.reason,status:"good"}}/>)}</Section></div></div></PageFrame>
}

export function RecommendationsRemediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.recommendations().then(setData)},[]); if(!data) return <PageFrame title="Opportunities & Recommendations"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Opportunities & Recommendations"><div className="grid grid-cols-3 gap-4"><Section title="Opportunity Funnel" icon={Target}>{data.pipeline.map((p:any)=><StatusRow key={p.stage} item={{name:p.stage,value:p.count,status:p.stage==="Accepted"||p.stage==="Implemented"?"good":"warn"}}/>)}</Section><Section title="Recommendation Queue" className="col-span-2">{data.recommendations.map((r:any)=><div key={r.title} className="mb-3 rounded-xl border p-3 text-[12px]"><div className="flex justify-between"><strong>{r.title}</strong><span className={cls(r.status)}>{r.status}</span></div><p className="mt-1 text-slate-600">{r.why}</p><div className="mt-2 flex items-center gap-2"><span>{r.priority}</span><span>{r.confidence}%</span><span>{r.impact}</span><button className="rounded bg-emerald-600 px-2 py-1 text-white">Accept</button><button className="rounded bg-red-600 px-2 py-1 text-white">Reject</button><button className="rounded bg-amber-500 px-2 py-1 text-white">Ignore</button><button className="rounded bg-blue-600 px-2 py-1 text-white">Modify</button></div></div>)}</Section><Section title="Learning Loop / ROI"><div className="grid grid-cols-2 gap-2 text-[12px]">{Object.entries(data.learning).map(([k,v]:any)=><div key={k} className="rounded-xl border bg-white p-3"><span className="text-slate-500">{k}</span><br/><strong>{v}</strong></div>)}</div></Section><Section title="Agent Trace" className="col-span-2"><AgentTrace items={data.agentTrace}/></Section></div></PageFrame>
}

export function GraphExplorerRemediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.graph().then(setData)},[]); if(!data) return <PageFrame title="Knowledge Graph Explorer"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Knowledge Graph Explorer"><div className="grid grid-cols-[1fr_360px] gap-4"><Section title="TigerGraph Relationship Explorer" icon={Network}><div className="relative h-[520px] rounded-xl bg-slate-950 p-6 text-white">{data.nodes.map((n:any,i:number)=><div key={n.id} className="absolute rounded-xl border border-blue-400 bg-slate-900 px-3 py-2 text-[11px]" style={{left:60+(i%3)*240, top:90+Math.floor(i/3)*150}}>{n.type}:<br/><strong>{n.label}</strong></div>)}<div className="absolute bottom-4 left-4 text-[11px] text-slate-400">Search · Filter · Expand Neighborhood · Path Finder</div></div></Section><div className="space-y-4"><Section title="Selected Node"><StatusRow item={{name:data.selected.name,value:`Score ${data.selected.score} · ${data.selected.relationships} relationships`,status:"good"}}/></Section><Section title="Edges">{data.edges.map((e:any)=><StatusRow key={e.source+e.target} item={{name:e.label,value:`${e.source} → ${e.target}`,status:"good"}}/>)}</Section></div></div></PageFrame>
}

export function FeaturesEmbeddingsRemediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.features().then(setData)},[]); if(!data) return <PageFrame title="Feature Store / Embeddings / Similarity"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Feature Store / Embeddings / Similarity"><div className="grid grid-cols-2 gap-4"><Section title="Feature Sets" icon={Database}>{data.featureSets.map((f:any)=><StatusRow key={f.name} item={{name:f.name,value:`${f.count} features · ${f.freshness}`,status:f.status}}/>)}</Section><Section title="Similarity Results" icon={Search}>{data.similarity.map((s:any)=><StatusRow key={s.name} item={{name:s.name,value:`${s.score}%`,reason:s.reason,status:"good"}}/>)}</Section><Section title="Embedding Projection" className="col-span-2" icon={GitBranch}><div className="relative h-72 rounded-xl border bg-white">{data.projection.map((p:any)=><div key={p.label} className="absolute rounded-full bg-blue-600 px-2 py-1 text-[10px] text-white" style={{left:`${p.x}%`, top:`${p.y}%`}}>{p.label}</div>)}</div></Section></div></PageFrame>
}

export function MemoryExplainabilityRemediation() {
  const [data,setData]=useState<any>(); useEffect(()=>{uiApi.memory().then(setData)},[]); if(!data) return <PageFrame title="Memory Timeline & Explainability"><div>Loading...</div></PageFrame>;
  return <PageFrame title="Memory Timeline & Explainability"><div className="grid grid-cols-2 gap-4"><Section title="Memory Timeline" icon={BrainCircuit}>{data.timeline.map((m:any)=><StatusRow key={m.title} item={{name:m.title,value:`${m.date} · ${m.type}`,status:m.status}}/>)}</Section><Section title="Explainability Path" icon={GitBranch}>{data.path.map((p:string,i:number)=><StatusRow key={p} item={{name:`${i+1}. ${p}`,value:"Evidence linked",status:i<3?"warn":"good"}}/>)}</Section><Section title="Evidence" className="col-span-2" icon={FileText}>{data.evidence.map((e:any)=><StatusRow key={e.source} item={{name:e.source,value:e.detail,status:"good"}}/>)}</Section></div></PageFrame>
}

export function DocumentIngestionRemediation() {
  const [name,setName]=useState("managed_account_playbook.pdf"); const [result,setResult]=useState<any>(); async function upload(){ setResult(await uiApi.ingest({document_name:name, document_type:name.split(".").pop(), content:"demo"})); }
  return <PageFrame title="Document Ingestion & Chroma Knowledge Pipeline"><div className="grid grid-cols-2 gap-4"><Section title="Upload Document" icon={Upload}><div className="rounded-xl border border-dashed p-8 text-center"><Upload className="mx-auto h-10 w-10 text-blue-600"/><input className="mt-4 h-9 w-full rounded-lg border px-3 text-[12px]" value={name} onChange={e=>setName(e.target.value)}/><button onClick={upload} className="mt-3 rounded-lg bg-blue-600 px-4 py-2 text-white">Simulate Upload + Index</button></div></Section><Section title="Pipeline Status" icon={Database}>{result ? <div className="space-y-2">{result.lineage.map((x:string)=><StatusRow key={x} item={{name:x,value:"completed",status:"good"}}/>)}<pre className="rounded bg-slate-100 p-2 text-[10px]">{JSON.stringify(result,null,2)}</pre></div> : <div className="text-[12px] text-slate-500">Upload a document to test chunking, embeddings, Chroma indexing, and graph lineage.</div>}</Section></div></PageFrame>
}
