from __future__ import annotations
import hashlib
import random
from app.ai.adapters.model_adapter import ModelAdapter

class MockModelAdapter(ModelAdapter):
    def generate_text(self, prompt: str, *, system_prompt: str | None = None) -> str:
        return "Demo response generated by local MockModelAdapter. Configure OPENAI_API_KEY to enable OpenAI-backed responses."

    def generate_json(self, prompt: str, *, system_prompt: str | None = None) -> dict:
        return {"title": "Demo AI Output", "summary": "Generated by local MockModelAdapter.", "confidence_score": 0.75, "source": "mock_adapter"}

    def embed_text(self, text: str) -> list[float]:
        seed = int(hashlib.sha256(text.encode("utf-8")).hexdigest(), 16) % (2**32)
        rng = random.Random(seed)
        vector = [rng.uniform(-1, 1) for _ in range(64)]
        norm = sum(v * v for v in vector) ** 0.5 or 1.0
        return [v / norm for v in vector]
