import { chromium } from "/workspaces/ip-demo-project/frontend/node_modules/playwright/index.mjs";
const OUT = new URL("../docs/qa_screenshots/session16/sweep/", import.meta.url).pathname;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
page.setDefaultTimeout(120000);
await page.goto("http://127.0.0.1:3000/revenue-analytics", { waitUntil: "domcontentloaded" });
await page.waitForSelector("text=Revenue Trend Explorer", { timeout: 120000 });
await page.waitForTimeout(25000);
await page.locator("text=Revenue Trend Explorer").first().scrollIntoViewIfNeeded();
await page.waitForTimeout(2000);
await page.screenshot({ path: OUT + "trend_explorer_focus.png", fullPage: false });
console.log("captured");
await browser.close();
